### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TimeseriesSurrogates.jl#118]
Before releasing 1.4 (I do not think we should count the in-place progress breaking change?) here's the remaining to-dos:

- [x] add changelog for all new methods
- [x] add changelog for the new in-place change
- [x] go through the docs once to be sure everything is a-ok
- [x] Actually increment Project.toml to 1.4. **EDIT: We'll go for 2.0.**

**Comment by kahaaga** [comment]
I guess we have some flexibility here. From the blog post about Julia release process:

> Minor releases are also where significant refactorings of internals go, since we should only be refactoring to the extent that is necessary for fixing bugs in patch releases. This means that if you're relying on some internal Julia stuff that's not public, your code might break in a minor release. This is allowed according to SemVer since the change isn't to a public API—so technically it can break at any time; but we will avoid this in patch releases, so minor releases will be where you have to watch out if you rely on internals somehow.

We're not affecting end users here, unless they rely on internals in some way (which I'm guessing not that many are), so this could be classified as a minor release.

About major releases it says:

> What a major release does allow, however, is fixing obvious API design mistakes—the kinds of bad, confusing APIs that everyone will be glad to be rid of. It also allows changing low-level things that will break some libraries, but which need to be broken in order to make really fundamental improvements to the language.

We did in fact fix an obvious design mistake: that the surrogates were not re-allocated. In that sense, we could consider this a major release, because we've finally settled on an API that is both optimally performant in terms of allocations, and user-friendly. It would also be nice for the paper to have a 2.0 release ready, which says «what's here is going to stay». 

Some packages are very generous with incrementing the major version, while others still haven't reached 1.0 status. I'm in favor of incrementing the major version, and let new methods signify versions `2.x` and so on.

**Comment by Datseris** [comment]
2.0 is also fine with me.

**Comment by kahaaga** [comment]
I'm tracking necessary changes in #119. If you have anything to add before I merge and tag, @Datseris, please add it to that branch. I'll try to thoroughly read the documentation sometime tomorrow.

**Comment by Datseris** [comment]
I've gone though all docs and did some minor improvements in #123. This is good to go.

**Comment by kahaaga** [comment]
> I've gone though all docs and did some minor improvements in #123. This is good to go.

Perfect. I'm tagging 2.0 straight away.

**Comment by kahaaga** [comment]
@JuliaRegistrator register
