### ISSUE TITLE
An API for significance

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TimeseriesSurrogates.jl#142]
We are developing [TransitionIndicators.jl](https://github.com/JuliaDynamics/TransitionIndicators.jl). There we use this surrogate package to test for significance. I coded the code below to bring simplicity in how we test for significance. But then I saw that CausalityTools.jl also has significance tests with surrogates and defines and exports types about it.

In the `SurrogateTest` of CausalityTools.jl it is not clear to me how independence is tested. In the end of the day you need to provide a true or false, which means you need to compare the true value with the surrogate distribution values. How do you do that precisely?

In any case, see the code above, which can be a basis on how to claim "significance" (in the sense that a real value is well outside the distribution of surrogates). Ideally, we won't duplicate code here and in CausalityTools.jl and we can define shared code in TimeseriesSurrogates.jl

```julia
using Statistics: quantile

"""
    SignificanceTest
Abstract type encompassing ways to test for significance in the function
[`significant`](@ref). Using its subtypes, the _real value_
derived from input data
is compared with the _distribution of the surrogate values_.
Subtypes:
- [`Quantile`](@ref)
- [`Sigma`](@ref)
"""
abstract type Significance end

"""
    significant(v::Real, s_vals::AbstractVector, q::Significance) → true/false
Return `true` if the value `v` is significant when compared to distribution of
surrogate values `s_vals` according to the criterion `q` (see [`SignificanceTest`](@ref)).
If not significant, return `false`.
If given `q::Real`, then [`Quantile`](@ref) is used.
"""
significant(v, s_vals, q::Real) = significant(v, s_vals, Quantile(q))

"""
    Quantile(q = 0.99, dir::Symbol = :updown) <: SignificanceTest
Significance is claimed by comparing the real value `v` with the `q`-th quantile of the
surrogate distribution. Three possibilities are provided depending on `dir`:
- `dir = :updown`: Significance is claimed if `v` is more than the `q`-th or is
  less than the `1-q`-th quantile
- `dir = :up`: if `v` is more than `q`-th
- `dir = :down`: if `v` is less than `1-q`-th
"""
struct Quantile <: Significance
    q::Float64
    dir::Symbol
end
Quantile(q = 0.99, dir = :updown) = Quantile(q, dir)

function significant(val, s_vals, quant::Quantile)
    q = quant.q
    if quant.dir == :updown
        low, high = quantile(s_vals, (1-q, q))
        return val < low || val > high
    elseif quant.dir == :up
        high = quantile(s_vals, q)
        return val > high
    elseif quant.dir == :down
        low = quantile(s_vals, 1-q)
        return val < low
    else
        error()
    end
end




"""
    Sigma(n::Real = 3, dir::Symbol = :updown) <: SignificanceTest
Significance is claimed by comparing the real value `v` with the
mean `μ` and standard deviation `σ` of the surrogate distribution.
Three possibilities are provided depending on `dir`:
- `dir = :updown`: significance is claimed if `v` is more than `μ + n*σ` or less than
  `μ - n*σ`.
- `dir = :up`: if `v` is more than `μ + n*σ`
- `dir = :down`: if `v` is less than `μ - n*σ`
"""
struct Sigma <: Significance
    n::Float64
    dir::Symbol
end
Sigma(n = 3, dir = :updown) = Sigma(n, dir)

using StatsBase: mean_and_std

function significant(val, s_vals, sigma::Sigma)
    n = sigma.n
    μ, σ = mean_and_std(s_vals)
    low, high = μ - n*σ, μ + n*σ
    if sigma.dir == :updown
        return val < low || val > high
    elseif sigma.dir == :up
        return val > high
    elseif sigma.dir == :down
        return val < low
    else
        error()
    end
end
```

**Comment by Datseris** [comment]
Perhaps we can do this with a nice type that implements surrogate significance tests. The type could be as follows:
```julia
struct SurrogateSignificance
    x::X # input
    f::F
    surrogate::Surrogate
    significance::Significance # as in my code snippet
    n::Int # number of surrogates to compute
end

# with f a function that takes one input (a timeseries) and returns a number
# to create the surrogfate disttribution and exact the real number from `x`
```

Then, we create the surrogate distribution of data with one function, and with another function (like the `significant` function above) we claim significance given the distribution. 

Thoughts?

**Comment by Datseris** [comment]
we can also create a `PValue` type that checks if the `p`-value is less than some threshold

**Comment by Datseris** [comment]
we can also make a `SurrogateSignificanceResult` that stores the surrogate distribution and real value so potentially other tests can be done as well without re-calculating the surrogate distribution.

**Comment by kahaaga** [comment]
Hey @Datseris! 

> In the `SurrogateTest` of CausalityTools.jl it is not clear to me how independence is tested. In the end of the day you need to provide a true or false, which means you need to compare the true value with the surrogate distribution values. How do you do that precisely?

## The way `SurrogateTest` works in CausalityTools

In CausalityTools, all independence tests are on the form:

```julia
Base.@kwdef struct SomeTest{A<:AssociationMeasure, E, R} <: IndependenceTest
    measure::A # The thing we want to quantify the significance of, e.g. `PearsonCorrelation()`, or `CMIShannon()`
    estimator::E = nothing # The estimator of the given measure, if relevant. Otherwise defaults to nothing
    rng::R = Random.default_rng()
    ... # Other relevant test parameters. 
end
```

The first two fields are mandatory, and are used for dispatch. The main function that computes significance is `independence(::IndependenceTest, x, y, [z, ...])`, where the two-argument version tests the significance of pairwise associations, and the three-argument version tests the significance of conditional associations.

`SurrogateTest` is just

```julia
Base.@kwdef struct SurrogateTest{M, E, R, S} <: IndependenceTest{M}
    measure::M
    est::E = nothing
    rng::R = Random.default_rng(),
    # Two extra fields that are specific to `SurrogateTest`
     surrogate::S = RandomShuffle(),
     nshuffles::Int = 100
end
```

Dispatch for `independence` with `SurrogateTest` is super simple. Example for generic pairwise comparisons:

```julia
function independence(test::SurrogateTest, x, y)
    (; measure, est, rng, surrogate, nshuffles) = test
    Î = estimate(measure, est, X, Y) # Original statistic
    Îs = zeros(nshuffles) # Surrogate statistics
    s = surrogenerator(x, surrogate, rng) # We only need to shuffle `x`
    for b in 1:nshuffles
        Îs[b] = estimate(measure, est, s(), Y)
    end
    # Define the p-value as the fraction of surrogate statistics that are more extreme
    # than the original statistic. 
    p = count(Î .<= Îs) / nshuffles

    return SurrogateTestResult(2, Î, Îs, p, nshuffles)
end
```

Because the desired "strictness of significance" is subjective, the test doesn't actually return a true/false statement. It returns a p-value instead, along with the null distribution. The user then, depending on their desired significance level, can compare this p-value to some pre-determined significance threshold `α`. If the significance level is e.g. `α = 0.05`,  if `p < α = 0.05`, we reject the null hypothesis of independence and accept the alternative hypothesis. If `p >= α = 0.05`, we can't reject the null hypothesis. This way, the user controls the strictness of the test.

Note that this is essentially just comparing if the original statistic is outside the one-sided `1-α` quantile of the null distribution. The p-value can be both left-sided, right-sided and double-sided, depending on context. For CausalityTools, we just use the right-sided (upper-tailed) p-value, because we are interested in checking whether we have quantified an association that lies *above* the null distribution.

The reason why I decided to go for p-values in CausalityTools.jl is that it is a single number, that it is completely generic, and it is also extremely commonly used in most other parametric and nonparametric hypothesis tests. For example, all tests in [https://juliastats.org/HypothesisTests.jl/stable/](@ref) implement the p-value. A surrogate test is "just another" nonparametric frequentist-based hypothesis test, so it is very natural that a `SurrogateTest` can be used to obtain a p-value. 

## Your proposal

You propose the surrogate test type

```julia
struct SurrogateSignificance
    x::X # input
    f::F
    surrogate::Surrogate
    significance::Significance # as in my code snippet
    n::Int # number of surrogates to compute
end
```

This goes proposal  goes one step further than `CausalityTools.SurrogateTest`: it provides `significant(original_statistic, surrogate_statistics, method)`, where `method` can be `Quantile`, `Sigma` or `PValue`, that gives you a yes/no answer for the question of significance. I like that idea.

I'd like to propose a slightly different solution, though:

```julia
```

>  we can also create a `PValue` type that checks if the p-value is less than some threshold

Yes.

> we can also make a SurrogateSignificanceResult that stores the surrogate distribution and real value so potentially other tests can be done as well without re-calculating the surrogate distribution.

Yes.

**Comment by kahaaga** [comment]
I have more comments and suggestions, but will post them below, because I need to try out some things first and see what could work with the existing API in CausalityTools.

**Comment by kahaaga** [comment]
```julia
struct SurrogateSignificance
    x::X # input
    f::F
    ... # parameters
end
```

@Datseris When defining  `SurrogateSignificance` as below, how do you intend to use it in practice? As an input argument to `significant`, e.g. `significant(::SurrogateSignificance)`?

**Comment by kahaaga** [comment]
We should design this generically enough that it is compatible not only with TransitionIndicators.jl and CausalityTools.jl, but also with ComplexityMeasures.jl. 

Can we do a Zoom call to discuss this, @Datseris?

**Comment by Datseris** [comment]
yes, sure, i can do a call. I'm free monday morning until 12 CET, otherwise again on tuesday any time during worktime.

**Comment by kahaaga** [comment]
> yes, sure, i can do a call. I'm free monday morning until 12 CET, otherwise again on tuesday any time during worktime.

Tuesday any time after 13 works for me.

**Comment by Datseris** [comment]
ok 13CET in my calendar!
