### ISSUE TITLE
Is the repo active?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TimeseriesSurrogates.jl#24]
Hi, I'd like to do some contributions to the repo. Is it active / maintained?

**Comment by kahaaga** [comment]
Hi, it is active indeed! Contributions are very welcome. What did you have in mind?

**Comment by Datseris** [comment]
I think the following would be useful:

1. Rework/rethink API: have central function `surrogate(s, method::Surrogate)` that creates a surrogate based on given method, e.g. `Shuffle`, `RandomAmplitude`, `RandomPhase`, `AAFT` , `IAAFT`, etc. It will make it more sensible to use, because changing method to generate timeseries in a `for `loop means changeing a funciton argument, not the function itself
2. improve plotting: the histograms must be semi-transparent, otherwise the histogram of the first timeseries is not seen.
3. add this method: https://journals.aps.org/pre/abstract/10.1103/PhysRevE.74.026205
4. add this method:  Small, M., Yu, D., & Harrison, R. G. (2001). Surrogate test for pseudoperiodic time series data. Physical Review Letters, 87(18), 188101-1-188101–188104. https://doi.org/10.1103/PhysRevLett.87.188101

You may also want to consider moving this to JuliaDynamics to get help from more people and more visibility.

**Comment by kahaaga** [comment]
## 1. New API: 

I like the `surrogate(s, method::Surrogate)` function and the associated types. Something like the following?  

```julia
abstract type Surrogate end

struct Shuffle
end

function surrogate(s, method::Shuffle)
    # code specific to the `Shuffle method` 
end
```

## 2. Plotting

Agreed, histograms should be semi-transparent. 

## 3 and 4. New methods

 I had a quick look at the papers, and both the surrogates for trended time series, and the pseudoperiodic surrogates are welcome contributions. 

### PPS surrogates

- I suggest a `PPS` type for the pseudoperiodic surrogates. 
- There is an embedding step involved here. It would be nice to allow for both uniform embeddings (i.e. fixed embedding lag) and nonuniform embeddings (i.e. different embedding lags for each of the components). The new `genembed` easily takes care of that. I suggest to have `τ` (integer or set of integers) and `d` (integer) as fields of the `PPS` type, so that the user may decide to either use a single, fixed `τ` or different `τ` for each coordinate axis of the embedding. 
- It could also be useful to allow automated choices of `d` and `τ` here if `τ` are set to strings, using `estimate_delay` and `estimate_dimension` from DynamicalSystems (e.g. `τ = "ac_zero"` uses an embedding where the embedding lag is determined by the first zero crossing of the autocorrelation function)`.

## Truncated fourier transform surrogates 

From the Nakamura et al. paper, there should be two separate methods: one for the truncated  Fourier transform surrogates (`TFTS`) and the symmetrized  version (`STFTS`). I think the selected frequency domain `fϵ` should be field of both these types.

Does that sound reasonable, @Datseris? 

## Joining JuliaDynamics

Moving the repository to JuliaDynamics is also a good idea. I'll transfer it to the organization straight away (I'm already added to the organization in the causalitytools team, right?).

**Comment by Datseris** [comment]
good, I've given you admin rights straight away. If you don't mind I am also part of the same team, so I can branch the repo in-place. But I won't be merging anything you don't approve!

**Comment by kahaaga** [comment]
Sure, sounds good!
